MineHouse_3_MapScripts::
	.byte 0

LiabaraHouse_EventScript_OldMan::
	msgbox LiabaraHouse_Text_OldMan MSGBOX_NPC
	end

LiabaraHouse_Text_OldMan:
	.string "These houses used to just be \n"
	.string "accomodation for workers in the mine. \l"
	.string "When it closed we had no idea \l"
	.string "where we'd go for work. But over \l"
	.string "the ensuing years, Grass type \l"
	.string "Pokémon moved in and created fields  \l"
	.string "we could farm. $"

LiabaraHouse_EventScript_OldWoman::
	msgbox LiabaraHouse_Text_OldWoman MSGBOX_NPC
	end

LiabaraHouse_Text_OldWoman:
	.string "It's so lovely to see \n"
	.string "Carraig back in the area. \l"
	.string "I remember how he used to play \l"
	.string "around the old mines, the little scamp. $"
