LiathbearradhCity_MapScripts::
	.byte 0

Liabara_EventScript_GymSign::
	msgbox LiabaraCity_Text_GymSign, MSGBOX_SIGN
	end

LiabaraCity_Text_GymSign:
	.string "Two sentences are written on this sign \n"
	.string "The first is stricken through \l"
	.string "with a line and reads: \p"
	.string "LEADER: Ethel \l"
	.string "The Saviour Botanist \p"
	.string "The second reads: \p"
	.string "LEADER: Carraig \l"
	.string "The Vagabond Archaeologist  $"

Liabara_EventScript_MuseumSign::
	msgbox LiabaraCity_Text_MuseumSign, MSGBOX_SIGN
	end
LiabaraCity_Text_MuseumSign:
	.string "Liabara City Museum: \n"
	.string "Exhibition and Mine Tour.  $"

Liabara_EventScript_LabSign::
	msgbox LiabaraCity_Text_LabSign, MSGBOX_SIGN
	end
LiabaraCity_Text_LabSign:
	.string "Residence and Labaratory of \n"
	.string "Professor E. Hawthorne.  $"

Liabara_EventScript_TownSign::
	msgbox LiabaraCity_Text_TownSign, MSGBOX_SIGN
	end
LiabaraCity_Text_TownSign:
	.string "Liabara City: Prospering \n"
	.string "in hard times.  $"
